[package]
name = "dashcam-rs"
version = "0.1.0"
authors = ["Ben Brown <bbrown1867@gmail.com>"]
edition = "2018"

[dependencies]
# Device support
cortex-m = "0.6.0"
cortex-m-rt = "0.6.10"

# HAL
embedded-hal = "0.2.3"
# stm32f7xx-hal = { version = "0.2.0", features = ["rt", "stm32f767"] }
stm32f7xx-hal = { path = "../stm32f7xx-hal", features = ["rt", "stm32f767"] }

# BSP
nucleof767zi-rs = { git = "https://github.com/bbrown1867/nucleof767zi-rs" }

# Runtime support
heapless = "0.5.5"
rtt-target = { version = "0.2.2", features = ["cortex-m"] }
